version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: togglefox-postgres
    environment:
      POSTGRES_DB: togglefox
      POSTGRES_USER: togglefox
      POSTGRES_PASSWORD: togglefox
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - togglefox-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U togglefox" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: togglefox-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - togglefox-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3

  # ToggleFox Application
  togglefox:
    build:
      dockerfile: Dockerfile
    container_name: togglefox-app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: jdbc:postgresql://postgres:5432/togglefox
      DATABASE_USERNAME: togglefox
      DATABASE_PASSWORD: togglefox
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - togglefox-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - togglefox_logs:/var/log/togglefox

volumes:
  postgres_data:
  redis_data:
  togglefox_logs:

networks:
  togglefox-network:
    driver: bridge