spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:h2:mem:togglefox;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  data:
    redis:
      host: localhost
      port: 6379
  
  flyway:
    enabled: false

logging:
  level:
    com.markin.togglefox: DEBUG
    org.springframework.web: DEBUG