spring:
  config:
    activate:
      on-profile: test
  
#  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
  
  flyway:
    enabled: false
  
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: WARN
    com.markin.togglefox: INFO
    org.springframework.test: DEBUG