spring:
  config:
    activate:
      on-profile: prod
  
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  file:
    name: /var/log/togglefox/application.log
  level:
    com.markin.togglefox: DEBUG
    org.springframework.web: DEBUG
    org.springdoc: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
