spring:
  config:
    activate:
      on-profile: prod
  
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.markin.togglefox: INFO
    org.springframework.web: WARN
  file:
    name: /var/log/togglefox/application.log